name: ci
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Generating Makefiles
      shell: bash
      run: |
        mkdir build
        cd build
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          cmake .. -G "NMake Makefiles"
        else
          cmake .. -G "Unix Makefiles"
        fi
    - name: Compiling
      shell: bash
      run: |
        cd build
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          nmake
        else
          make
        fi
    - name: Running Tests
      shell: bash
      run: |
        export CPPILLR=$(pwd)/build/cppillr
        cd tests && bash run.sh
